server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fsrs_vocab?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 128ghe980@ZKX
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    root: info
